project:
  type: website

website:
  title: "Forecasting Anomalies in AtHub’s Stock Behavior"
  favicon: "images/favicon.png"
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU25/final-project-zhu
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light:
        - flatly
        - style/customtheming.scss
      dark:
        - darkly
        - style/customtheming.scss

    toc: true

execute:
  freeze: auto
